
name: Sync Fork	

# Controls when the action will run. Triggers the workflow on push or pull request	
# events but only for the master branch	
on:	
  workflow_dispatch:	
  schedule:	
    - cron: '*/30 * * * *'	

# A workflow run is made up of one or more jobs that can run sequentially or in parallel	
jobs:	
  sync:	
     runs-on: ubuntu-latest	
     steps:	
      - uses: TG908/fork-sync@v1.1	
        with:	
          github_token: ${{ secrets.GITHUB_TOKEN }}	
          owner: abhisekp	
          base: master	
          head: master
